	ORG	0
	BSF	STATUS,5
	CLRF	TRISA
	CLRF	TRISB
	MOVLW	B'10000011'
	MOVWF	OPTION
	BSF	PORTA,0
	BSF	PORTA,1
	BSF	PORTA,2
	BSF	PORTA,3

	BCF	PORTB,0
	BCF	PORTB,1
	BCF	PORTB,2
	BCF	PORTB,3
	BCF	PORTB,4
	BCF	PORTB,5
	BCF	PORTB,6
	BCF	PORTB,7
	
	BCF	STATUS,5
	CLRF	PORTA
	CLRF	PORTB
	MOVLW	.1
	MOVWF	1BH		;Permanentes
	MOVLW	.2
	MOVWF	1DH		;Permanentes
	MOVLW	.3
	MOVWF	3AH		;Permanentes
	MOVLW	.4
	MOVWF	3BH		;Permanentes
	MOVLW	.5
	MOVWF	4AH		;Permanentes
	MOVLW	.6
	MOVWF	4BH		;Permanentes
	MOVLW	.7
	MOVWF	4CH		;Permanentes

	MOVLW	.1
	MOVWF	1AH		;el que varia

INICIO	BTFSS	PORTA,0
	GOTO	INICIO
BUE	BTFSC	PORTA,0
	GOTO	BUE
	BTFSS	PORTA,2
	GOTO	DOVO
NIN	BTFSC	PORTA,2
	GOTO	NIN
	GOTO	ALOTRO1

ALOTRO1	MOVFW	1BH		;.1
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NO1
	INCF	1AH,F
	GOTO	DOVO
NO1	MOVFW	1DH		;.2
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NO2
	INCF	1AH,F
	GOTO	DOVO
NO2	MOVFW	3AH		;.3
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NO3
	INCF	1AH,F
	GOTO	DOVO
NO3	MOVFW	3BH		;.4
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NO4
	INCF	1AH,F
	GOTO	DOVO
NO4	MOVFW	4AH		;.5
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NO5
	INCF	1AH,F
	GOTO	DOVO
NO5	MOVFW	4BH		;.6
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	DOVO
	INCF	1AH,F
	GOTO	DOVO

DOVO	BTFSS	PORTA,3
	GOTO	PRIRO
NIIN	BTFSC	PORTA,3
	GOTO	NIIN
	GOTO	ALOTRO2
ALOTRO2	MOVFW	4CH		;.7
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NOO1
	DECF	1AH,F
	GOTO	PRIRO
NOO1	MOVFW	4BH		;.6
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NOO2
	DECF	1AH,F
	GOTO	PRIRO
NOO2	MOVFW	4AH		;.5
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NOO3
	DECF	1AH,F
	GOTO	PRIRO
NOO3	MOVFW	3BH		;.4
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NOO4
	DECF	1AH,F
	GOTO	PRIRO
NOO4	MOVFW	3AH		;.3
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	NOO5
	DECF	1AH,F
	GOTO	PRIRO
NOO5	MOVFW	1DH		;.2
	SUBWF	1AH,W
	BTFSS	STATUS,2
	GOTO	PRIRO
	DECF	1AH,F
	GOTO	PRIRO
PRIRO	GOTO	BUE
	END